[build-system]
requires = [ "setuptools", "setuptools-scm",]
build-backend = "setuptools.build_meta"

[project]
name = "test"
version = "0.0.6"
description = "Update a toml value from a CLI"
readme = "README.md"
requires-python = ">=3.7"
keywords = [ "toml", "requirements", "update",]
classifiers = [ "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 3",]
dependencies = [ "toml",]
[[project.authors]]
name = "Jake Cyr"
email = "cyrjake@gmail.com"

[project.license]
text = "MIT"

[project.scripts]
update-toml = "update_toml.main:main"

[tool.distutils.bdist_wheel]
universal = true
